[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

# Email sync cron job - runs every 5 minutes  
[[services]]
name = "email-sync"
cronSchedule = "*/5 * * * *"
command = "python -m flask --app main sync-emails"